# Generated by Django 5.2.10 on 2026-01-10 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(blank=True, help_text='ISO 3166-1 alpha-2, e.g. GB, IE', max_length=2)),
                ('is_player', models.BooleanField(default=True)),
                ('is_club_admin', models.BooleanField(default=False)),
                ('is_platform_admin', models.BooleanField(default=False)),
                ('consent_accepted', models.BooleanField(default=False)),
                ('consent_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
